### ISSUE TITLE
helix 23.03 issues

### ISSUE THREAD

**Issue by God-damnit-all** [jharrilim/chocolatey-packages#1]
It seems that 23.03 was overlooked in the moderation approval queue since 22.12 was submitted simultaneously.

https://community.chocolatey.org/packages/helix/23.03

I'm not sure how the process works, but maybe you should poke them.

**Comment by God-damnit-all** [comment]
I just realized that while the latest version is marked as 22.12, it installs 23.03 anyway.

**Comment by jharrilim** [comment]
Closing since this seems to be resolved as of 23.05
