### ISSUE TITLE
Please Make 23.05 Available

### ISSUE THREAD

**Issue by Joe-Zer0** [jharrilim/chocolatey-packages#2]
Please make 23.05 available in chocolate. Thanks!

**Comment by jharrilim** [comment]
Resent verification here:
https://community.chocolatey.org/packages/helix/23.05

Hopefully will pass all checks soon!

**Comment by Joe-Zer0** [comment]
Thanks!

**Comment by Joe-Zer0** [comment]
https://community.chocolatey.org/packages/helix/23.05
(Maintainer responded, waiting for review/Maintainer update)
Is there something else you have to do, or are we just waiting on choco?

**Comment by jharrilim** [comment]
> https://community.chocolatey.org/packages/helix/23.05 (Maintainer responded, waiting for review/Maintainer update) Is there something else you have to do, or are we just waiting on choco?

We are just waiting, however I sent another message just in case the other got lost.

**Comment by jharrilim** [comment]
Looks like it's live now!

**Comment by Joe-Zer0** [comment]
Awesome! Thank you!
