### ISSUE TITLE
Helix version

### ISSUE THREAD

**Issue by Sylvanbain** [jharrilim/chocolatey-packages#3]
Hello,

Chocolatey says the latest version is 23.10, while I see your repo says the latest one is 24.03?

Can you please confirm? Thank you :)

**Comment by jharrilim** [comment]
Just confirming that I have tried this so far but to no avail. Chocolatey packages have updated to a newer `choco` CLI version (2.2.2), and AppVeyor is on 1.4.0. Once this issue[^1] is addressed, I can retry publishing using the new version. 

[^1]: https://github.com/appveyor/ci/issues/3917

**Comment by Sylvanbain** [comment]
I guess we all just have to wait. Thank you for the clarification

**Comment by jharrilim** [comment]
Actually, as a workaround, I just built and pushed the package locally. Under this new choco version, it's normalizing the version as `24.3.0`. It seems to have passed the automated tests this time. The status for it can be tracked here:

https://community.chocolatey.org/packages/helix/24.3.0

**Comment by jharrilim** [comment]
The package has been approved now. You may use this to upgrade:

```shell
choco upgrade helix
```
